# Generated by Django 5.2 on 2025-04-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('BookInfo', models.CharField(max_length=100)),
                ('Bookimg', models.ImageField(null=True, upload_to='Books')),
                ('BookPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='History_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hstr_bookname', models.CharField(max_length=100)),
                ('hstr_bookinfo', models.CharField(max_length=100)),
                ('hstr_bookdsc', models.CharField(max_length=100)),
                ('hstr_bookimg', models.ImageField(blank=True, null=True, upload_to='storyBooks')),
                ('hstr_bookPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='story_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_bookname', models.CharField(max_length=100)),
                ('str_bookinfo', models.CharField(max_length=100)),
                ('str_bookdsc', models.CharField(max_length=100)),
                ('str_bookimg', models.ImageField(blank=True, null=True, upload_to='storyBooks')),
                ('str_bookPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
