# Generated by Django 5.2 on 2025-04-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_data',
            name='BookPrice',
        ),
        migrations.RemoveField(
            model_name='history_book',
            name='hstr_bookPrice',
        ),
        migrations.RemoveField(
            model_name='story_book',
            name='str_bookPrice',
        ),
    ]
