# Generated by Django 5.2 on 2025-04-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
    ]
