# Generated by Django 5.2 on 2025-04-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
